sudo: true
language: haskell

cabal: "3.2"

matrix:
  include:
  - ghc: 8.10.1

install:
  - ghc --version
  - cabal --version
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks

script:
  - cabal new-test --enable-tests

notifications:
  email: false